In [1]:
import numpy  as np

In [2]:
 
def vander_monde(in_vect,n,increase=False):
    
    if not increase:
        result=np.array([j**(n-i-1) for j in in_vect for i in range(n)]).reshape(in_vect.size,n)
    elif increase:
        result=np.array([j**i for j in in_vect for i in range(n)]).reshape(in_vect.size,n)
    
    return result

x=np.array([1,2,3,4])
print(vander_monde(x,3,False))
print('\n')
x=np.array([2,3,4,5,6])
print(vander_monde(x,4,True))
                

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


[[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]]


In [3]:
x=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3

In [4]:
#no.of values in moving average are; n-k+1
n=(x.size)-k+1
n

11

In [5]:
result=[]
for i in range(n):
    result.append((x[i]+x[i+1]+x[i+2])/k)
result=[round(num,2) for num in result]
result

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]